name: Fusion Audio Vidéo

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'URL de la vidéo MP4'
        required: true
        type: string
      audio_url:
        description: 'URL du MP3'
        required: true
        type: string

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install FFmpeg
        run: sudo apt update && sudo apt install -y ffmpeg

      - name: Run merge script
        run: bash merge.sh "${{ github.event.inputs.video_url }}" "${{ github.event.inputs.audio_url }}"
